# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: d:/Master_local/TFM/Prueba1/prueba_v1.0.srcs/sources_1/bd/design_1/ip/design_1_system_ila_0_2/design_1_system_ila_0_2.xci
# IP: The module: 'design_1_system_ila_0_2' is the root of the design. Do not add the DONT_TOUCH constraint.

# Block Designs: d:/Master_local/TFM/Prueba1/prueba_v1.0.gen/sources_1/bd/design_1/ip/design_1_system_ila_0_2/bd_0/bd_378d.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_378d || ORIG_REF_NAME==bd_378d} -quiet] -quiet

# IP: d:/Master_local/TFM/Prueba1/prueba_v1.0.gen/sources_1/bd/design_1/ip/design_1_system_ila_0_2/bd_0/ip/ip_0/bd_378d_ila_lib_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_378d_ila_lib_0 || ORIG_REF_NAME==bd_378d_ila_lib_0} -quiet] -quiet

# XDC: d:/Master_local/TFM/Prueba1/prueba_v1.0.gen/sources_1/bd/design_1/ip/design_1_system_ila_0_2/bd_0/ip/ip_0/ila_v6_2/constraints/ila_impl.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_378d_ila_lib_0 || ORIG_REF_NAME==bd_378d_ila_lib_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: d:/Master_local/TFM/Prueba1/prueba_v1.0.gen/sources_1/bd/design_1/ip/design_1_system_ila_0_2/bd_0/ip/ip_0/ila_v6_2/constraints/ila.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_378d_ila_lib_0 || ORIG_REF_NAME==bd_378d_ila_lib_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: d:/Master_local/TFM/Prueba1/prueba_v1.0.gen/sources_1/bd/design_1/ip/design_1_system_ila_0_2/bd_0/ip/ip_0/bd_378d_ila_lib_0_ooc.xdc

# XDC: d:/Master_local/TFM/Prueba1/prueba_v1.0.gen/sources_1/bd/design_1/ip/design_1_system_ila_0_2/bd_0/bd_378d_ooc.xdc

# XDC: d:/Master_local/TFM/Prueba1/prueba_v1.0.gen/sources_1/bd/design_1/ip/design_1_system_ila_0_2/design_1_system_ila_0_2_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_system_ila_0_2'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: d:/Master_local/TFM/Prueba1/prueba_v1.0.srcs/sources_1/bd/design_1/ip/design_1_system_ila_0_2/design_1_system_ila_0_2.xci
# IP: The module: 'design_1_system_ila_0_2' is the root of the design. Do not add the DONT_TOUCH constraint.

# Block Designs: d:/Master_local/TFM/Prueba1/prueba_v1.0.gen/sources_1/bd/design_1/ip/design_1_system_ila_0_2/bd_0/bd_378d.bd
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_378d || ORIG_REF_NAME==bd_378d} -quiet] -quiet

# IP: d:/Master_local/TFM/Prueba1/prueba_v1.0.gen/sources_1/bd/design_1/ip/design_1_system_ila_0_2/bd_0/ip/ip_0/bd_378d_ila_lib_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_378d_ila_lib_0 || ORIG_REF_NAME==bd_378d_ila_lib_0} -quiet] -quiet

# XDC: d:/Master_local/TFM/Prueba1/prueba_v1.0.gen/sources_1/bd/design_1/ip/design_1_system_ila_0_2/bd_0/ip/ip_0/ila_v6_2/constraints/ila_impl.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_378d_ila_lib_0 || ORIG_REF_NAME==bd_378d_ila_lib_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: d:/Master_local/TFM/Prueba1/prueba_v1.0.gen/sources_1/bd/design_1/ip/design_1_system_ila_0_2/bd_0/ip/ip_0/ila_v6_2/constraints/ila.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_378d_ila_lib_0 || ORIG_REF_NAME==bd_378d_ila_lib_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: d:/Master_local/TFM/Prueba1/prueba_v1.0.gen/sources_1/bd/design_1/ip/design_1_system_ila_0_2/bd_0/ip/ip_0/bd_378d_ila_lib_0_ooc.xdc

# XDC: d:/Master_local/TFM/Prueba1/prueba_v1.0.gen/sources_1/bd/design_1/ip/design_1_system_ila_0_2/bd_0/bd_378d_ooc.xdc

# XDC: d:/Master_local/TFM/Prueba1/prueba_v1.0.gen/sources_1/bd/design_1/ip/design_1_system_ila_0_2/design_1_system_ila_0_2_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_system_ila_0_2'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
